import { CampoExtraMediosPago } from "./types/campoExtraMediosPago";
import { CampoExtraMediosPagoConverter } from "./types/campoExtraMediosPagoConverter";

exports.CampoExtraMediosPago = CampoExtraMediosPago;
exports.CampoExtraMediosPagoConverter = CampoExtraMediosPagoConverter;
// exports.cliente = require("./types/cliente");
// exports.empresa = require("./types/empresa");
// exports.local = require("./types/local");
// exports.mediosPago = require("./types/mediosPago");
// exports.moneda = require("./types/moneda");
// exports.opcionesGenerales = require("./types/opcionesGenerales");
// exports.opcionesGeneralesServicios = require("./types/opcionesGeneralesServicios");
// exports.productosListasPrecio = require("./types/productosListasPrecio");
// exports.productosRubros = require("./types/productosRubros");
// exports.servicio = require("./types/servicio");
// exports.serviciosListasPrecio = require("./types/serviciosListasPrecio");
// exports.serviciosPrecios = require("./types/serviciosPrecios");
// exports.serviciosRubros = require("./types/serviciosRubros");
// exports.tasaIVA = require("./types/tasaIVA");
// exports.unidad = require("./types/unidad");
// exports.usuario = require("./types/usuario");
// exports.usuariosSistemaInvitacion = require("./types/usuariosSistemaInvitacion");
